graph TD
    %% 特殊科技列表

    %% 战术少女
    %% 战术少女是经过专门训练的战斗专家，从调教学院最优秀的素体中选出，一名训练有素、装备充足的战术少女可以独自对抗 15 名精英男性特战队
    %% 在情色技术和生物工程的帮助下，战术少女的耐力、柔韧性和快速反应能力得到了显著提升。
    %% 为了适应复杂的战斗情况，战术少女的身体经过了特殊的义体改造，膝关节和腿部由高速合金钢制成，
    %% 同时还安装了特殊的运动传感器，用于实时监测战斗状态和调整运动策略。手臂被替换为生化合成的义体，
    %% 够提供更强的力量和柔韧性的同时保持了灵敏的感觉，手掌植入了生化数据线，可以与智能武器连接。
    %% 战术少女的下体处于持久的刺激之中，特制的震动棒插入小穴之中，阴蒂被按摩器紧紧夹住，超长的假屌深入后穴之中，用于生产足够的情欲能量供义体和武器使用。
    %% 紧急情况下，植入体内的催情剂和肾上腺素注射器可以迅速提高战术少女的情欲能量和爆发力。
    subgraph TacticGirl [战术少女]
    direction TB
    TG1["1936 战术少女原型"] --> TGUp1["1937 强化活血泵"]
    TG1 --> TGUp2["1938 人工第二心脏"]
    TG1 --> TGUp3["1938 催情剂和肾上腺素"]
    TG2["1939 战术少女"] --> TG3["1940 综合强化"] --> TG4["1942 高级战术少女"]
    TGUp1 --> TG2
    TGUp2 --> TG2
    TGUp3 --> TG2
    end

    subgraph MilkingTech [榨乳技术]
    direction TB
    M1["1937 榨乳机"]
    MU1["1938 空孕催乳剂"]
    MU2["1938 强制受精"]
    MU3["1938 快感催产剂"]
    M1 --> MU1
    M1 --> MU2
    M1 --> MU3
    M2["1939 榨乳机"]
    MU1 --> M2
    MU2 --> M2
    MU3 --> M2
    end

    subgraph SexToy [性爱玩具]
    direction TB
    ST1["1938 性爱玩具"]
    ST2["1939 性爱玩具"]
    ST3["1940 性爱玩具"]
    ST4["1942 高级性爱玩具"]
    ST1 --> ST2
    ST2 --> ST3
    ST3 --> ST4
    end

    subgraph Futanarization [扶她化改造]
    direction TB
    FT1["1936 实验性原型机"]
    end